app = 'wg-dc-bot'
primary_region = 'ams'

[build]
dockerfile = 'Dockerfile'

[env]
DISCORD_BOT_TOKEN = "DISCORD_BOT_TOKEN"

[processes]
app = "python main.py"

[[vm]]
memory = '256mb'
swap_size_mb = 512  # TO JEST KLUCZOWA ZMIANA
cpu_kind = 'shared'
cpus = 1
