app = 'wg-dc-bot'
primary_region = 'ams'

[build]
dockerfile = 'Dockerfile'

[env]
# Tutaj zostanie wstrzyknięty Twój token z ustawień Fly.io
DISCORD_BOT_TOKEN = "TWÓJ_TOKEN_Z_USTAWIEŃ"

# CAŁĄ SEKCJĘ [[http_service]] USUWAMY, BO BOTA NIE TRZEBA "ODPYTYWAĆ" O STRONĘ WWW

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
